import React, { useState } from 'react';
import { PRDSection, BrandingData } from '../types';
import { jsPDF } from "jspdf";
import { Button } from './Button';

interface PRDDisplayProps {
  sections: PRDSection[];
  branding?: BrandingData; // Optional branding for HTML export styling
}

const SimpleMarkdown: React.FC<{ content: string }> = ({ content }) => {
  const lines = content.split('\n');
  return (
    <div className="space-y-2 text-slate-300 leading-relaxed">
      {lines.map((line, idx) => {
        if (line.startsWith('# ')) return <h3 key={idx} className="text-2xl font-bold text-white mt-6 mb-3">{line.replace('# ', '')}</h3>;
        if (line.startsWith('## ')) return <h4 key={idx} className="text-xl font-semibold text-white mt-5 mb-2">{line.replace('## ', '')}</h4>;
        if (line.startsWith('### ')) return <h5 key={idx} className="text-lg font-medium text-indigo-300 mt-4 mb-2">{line.replace('### ', '')}</h5>;
        if (line.trim().startsWith('- ')) return <li key={idx} className="ml-4 list-disc pl-1">{line.replace('- ', '')}</li>;
        
        const parts = line.split(/(\*\*.*?\*\*)/g);
        return (
          <p key={idx} className="min-h-[1rem]">
            {parts.map((part, pIdx) => {
              if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={pIdx} className="text-white font-semibold">{part.slice(2, -2)}</strong>;
              }
              return part;
            })}
          </p>
        );
      })}
    </div>
  );
}

export const PRDDisplay: React.FC<PRDDisplayProps> = ({ sections, branding }) => {
  const [activeSectionId, setActiveSectionId] = useState(sections[0]?.id);
  const [isExporting, setIsExporting] = useState(false);

  const activeSection = sections.find(s => s.id === activeSectionId) || sections[0];

  const handleExportPDF = () => {
    setIsExporting(true);
    const doc = new jsPDF();
    let yPos = 20;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const maxWidth = 170;

    doc.setFontSize(22);
    doc.text("Product Requirements Document", margin, yPos);
    yPos += 15;

    doc.setFontSize(10);
    doc.text(`Generated by SpecForge AI on ${new Date().toLocaleDateString()}`, margin, yPos);
    yPos += 20;

    sections.forEach((section) => {
        if (yPos > pageHeight - 30) {
            doc.addPage();
            yPos = 20;
        }
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text(section.title, margin, yPos);
        yPos += 10;

        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        
        const cleanContent = section.content
            .replace(/\*\*(.*?)\*\*/g, '$1')
            .replace(/#+\s/g, '')
            .replace(/-\s/g, '• ');

        const splitText = doc.splitTextToSize(cleanContent, maxWidth);
        
        for (let i = 0; i < splitText.length; i++) {
             if (yPos > pageHeight - 20) {
                 doc.addPage();
                 yPos = 20;
             }
             doc.text(splitText[i], margin, yPos);
             yPos += 6;
        }
        yPos += 10;
    });

    doc.save("specforge-prd.pdf");
    setIsExporting(false);
  };

  const handleExportMarkdown = () => {
    let mdContent = `# Product Requirements Document\n\nGenerated by SpecForge AI\n\n---\n\n`;
    sections.forEach(s => {
      mdContent += `${s.content}\n\n`;
    });
    
    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'specforge-prd.md';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportHTML = () => {
    const palette = branding?.palette;
    const primaryColor = palette?.primary || '#4f46e5';
    const bgColor = palette?.background || '#ffffff';
    const textColor = palette?.text || '#1e293b';
    const accentColor = palette?.accent || '#6366f1';

    let htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Product Requirements Document</title>
<style>
  :root {
    --primary: ${primaryColor};
    --bg: ${bgColor};
    --text: ${textColor};
    --accent: ${accentColor};
  }
  body {
    font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    color: var(--text);
    background: var(--bg);
    max-width: 900px;
    margin: 0 auto;
    padding: 40px 20px;
  }
  h1, h2, h3 { color: var(--primary); }
  h1 { border-bottom: 2px solid var(--accent); padding-bottom: 10px; margin-bottom: 30px; }
  h2 { margin-top: 40px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 8px; }
  strong { color: var(--primary); }
  code { background: #f1f5f9; padding: 2px 5px; rounded: 4px; font-family: monospace; }
  .timestamp { color: #64748b; font-size: 0.9em; margin-bottom: 40px; }
</style>
</head>
<body>
  <h1>Product Requirements Document</h1>
  <div class="timestamp">Generated by SpecForge AI on ${new Date().toLocaleDateString()}</div>
`;

    sections.forEach(s => {
        // Convert basic markdown to HTML for the export
        let contentHtml = s.content
            .replace(/^# (.*$)/gim, '<h3>$1</h3>')
            .replace(/^## (.*$)/gim, '<h4>$1</h4>')
            .replace(/^### (.*$)/gim, '<h5>$1</h5>')
            .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
            .replace(/^\- (.*$)/gim, '<li>$1</li>')
            .replace(/\n/gim, '<br />');
        
        // Wrap lists (simplistic, assumes contiguous lists)
        // A robust parser would be better, but for this snippet:
        contentHtml = contentHtml.replace(/(<li>.*<\/li>)/gim, '<ul>$1</ul>').replace(/<\/ul><br \/><ul>/gim, '');

        htmlContent += `
  <section>
    <h2>${s.title}</h2>
    <div>${contentHtml}</div>
  </section>
`;
    });

    htmlContent += `
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'specforge-prd.html';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="flex flex-col lg:flex-row h-full min-h-[600px] border border-slate-700 rounded-xl overflow-hidden bg-slate-850">
      {/* Sidebar Navigation */}
      <div className="w-full lg:w-64 bg-slate-900 border-b lg:border-b-0 lg:border-r border-slate-700 p-4 flex flex-col">
        <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4 px-2">Table of Contents</h3>
        <nav className="space-y-1 flex-1 overflow-y-auto mb-4 custom-scrollbar">
          {sections.map((section) => (
            <button
              key={section.id}
              onClick={() => setActiveSectionId(section.id)}
              className={`w-full text-left px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                activeSectionId === section.id
                  ? 'bg-indigo-600/20 text-indigo-300'
                  : 'text-slate-400 hover:bg-slate-800 hover:text-white'
              }`}
            >
              {section.title}
            </button>
          ))}
        </nav>
        
        <div className="space-y-2 mt-auto pt-4 border-t border-slate-800">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider px-2">Export Options</h3>
            <Button onClick={handleExportPDF} variant="secondary" className="w-full text-xs" disabled={isExporting}>
                Download PDF
            </Button>
            <div className="grid grid-cols-2 gap-2">
                <Button onClick={handleExportMarkdown} variant="outline" className="text-xs px-2">
                    Markdown
                </Button>
                <Button onClick={handleExportHTML} variant="outline" className="text-xs px-2">
                    HTML
                </Button>
            </div>
        </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 p-8 overflow-y-auto bg-slate-850">
        {activeSection ? (
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-bold text-white mb-6 border-b border-slate-700 pb-4">
              {activeSection.title}
            </h2>
            <SimpleMarkdown content={activeSection.content} />
          </div>
        ) : (
          <div className="text-center text-slate-500 mt-20">No content available.</div>
        )}
      </div>
    </div>
  );
};